name: Build and Test so_long_linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev \
          libxext-dev \
          libxrender-dev \
          libxrandr-dev \
          xvfb \
          x11-utils

    - name: Build the project
      run: make bonus

    - name: Run the game with virtual display
      run: |
        chmod +x ./so_long
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" ./so_long mapbig.ber
